"""Every registered app gets a real icon tile — not a letter.

`appIcon(id)` looks the id up in `ICONS` and, failing that, falls back to
`iconTile()`: the app's `icon` string drawn as text on a generated gradient, or —
when that field is empty — a single monogram letter. Both fallbacks are deliberate
and correct for **user-built** apps, which the OS knows nothing about in advance.

For the OS's own apps they are a gap nobody notices while adding one: the app works,
it opens, it has a name. It just looks unfinished next to the 37 that had a proper
duotone tile, and the System group of the deck is exactly where they all appear at
once. Eight had slipped through — `permissions` and `train` were rendering as the
letters P and T.

The check is on the SOURCE, because that is where an icon is added; `index.html` is
generated and `tests/test_ui_build.py` already fails if it is stale.
"""

import re
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parent.parent / "agentos" / "ui" / "src" / "js"
ICONS_JS = (SRC / "01-app-icons.js").read_text()
REGISTRY_JS = (SRC / "05-apps-registry.js").read_text()


def icon_keys() -> set[str]:
    body = ICONS_JS.split("const ICONS={", 1)[1].split("\n};", 1)[0]
    return set(re.findall(r"^\s{2}([a-z][a-z0-9_]*)\s*:\s*\[", body, re.M))


def app_ids() -> set[str]:
    return set(re.findall(r"^\s{2}([a-z][a-z0-9_]*)\s*:\s*\{\s*id:", REGISTRY_JS, re.M))


def test_the_two_lists_were_actually_found():
    """Both parsers key off formatting. If either silently matches nothing, every
    assertion below passes while checking nothing at all."""
    assert len(icon_keys()) > 30, "the ICONS table did not parse"
    assert len(app_ids()) > 30, "the APPS registry did not parse"


def test_every_registered_app_has_its_own_icon_tile():
    missing = sorted(app_ids() - icon_keys())
    assert not missing, (
        "these apps fall back to a text glyph or a monogram letter instead of a "
        f"duotone tile: {missing} — add each to ICONS in 01-app-icons.js")


def test_no_icon_is_defined_for_an_app_that_no_longer_exists():
    """Dead entries are harmless but they hide the live ones: the next person to ask
    'is everything covered?' has to work out which half of the diff is real."""
    orphans = sorted(icon_keys() - app_ids())
    assert not orphans, f"ICONS defines tiles for apps that are gone: {orphans}"


@pytest.mark.parametrize("key", sorted(icon_keys()))
def test_each_tile_is_a_two_stop_gradient_and_an_svg_path(key):
    """The shape the renderer requires: [from, to, svg]. A malformed entry does not
    throw — `glyphTile` interpolates undefined into the style and the tile renders
    as a transparent box, which reads as 'the icon is missing' all over again."""
    body = ICONS_JS.split("const ICONS={", 1)[1].split("\n};", 1)[0]
    m = re.search(rf"^\s{{2}}{key}\s*:\s*\[(.*?)\],\s*$", body, re.M | re.S)
    assert m, f"{key} is not a single-line [from,to,svg] entry"
    entry = m.group(1)
    colours = re.findall(r"'(#[0-9A-Fa-f]{6})'", entry)
    assert len(colours) >= 2, f"{key} needs two gradient stops, found {colours}"
    assert "<path" in entry or "<circle" in entry or "<rect" in entry, (
        f"{key} has no drawable SVG geometry")


@pytest.mark.parametrize("key", sorted(icon_keys()))
def test_each_tile_draws_something(key):
    """The geometry element is present and non-trivial.

    There is deliberately no coordinate-bounds check here. An earlier version tried
    one and was wrong twice over: it first measured the digits inside `#4AA9FF`, and
    then, once that was fixed, flagged 26 shipped icons because lowercase SVG
    commands take RELATIVE deltas — `-3.6` in a `l-3.6` is inside the box, not
    outside it. Telling absolute coordinates from relative ones needs a real path
    parser, which is not worth writing for a test when the actual check is looking
    at the tiles rendered (see the strip in tests/fixtures, regenerated by hand).
    """
    body = ICONS_JS.split("const ICONS={", 1)[1].split("\n};", 1)[0]
    entry = re.search(rf"^\s{{2}}{key}\s*:\s*\[(.*?)\],\s*$", body, re.M | re.S).group(1)
    parts = entry.split("','")
    assert len(parts) >= 3, f"{key} is not [from,to,svg]"
    svg = "','".join(parts[2:]).rstrip("'")
    assert len(svg) > 20, f"{key} has a suspiciously empty glyph"
