"""The WhatsApp Web transport: this machine, as a linked device.

The Cloud API (agentos/whatsapp.py) is the official way in, and it is a lot to ask
of somebody who just wants their agent on WhatsApp: a Meta developer account, a
public HTTPS webhook, and a 24-hour window that silently swallows any message the
user did not invite. This transport asks for a QR code.

It is **unofficial**, and that is stated everywhere it is offered rather than
buried. WhatsApp does not support automating a linked device and has banned
accounts for it; the consent screen says so, in those words, and recommends a
spare number. Nothing here installs or connects without that screen being read.

WHY A NODE SIDECAR
==================
There is no maintained Python client for the WhatsApp Web protocol. Baileys (MIT)
is the one that is actually kept working, and it is Node. So the bridge is a small
Node script AgentOS writes and runs, and Python drives it.

The seam is **newline-delimited JSON over stdio**, not a port. Three reasons, all
learned the expensive way from `wayvnc` and the MCP servers:

  - No second listener means nothing new to authenticate, nothing to bind, and no
    port to collide. WhatsApp credentials on a loopback port with no auth would be
    a full account takeover for anything else on the machine.
  - The child dies with the parent. A bridge that outlives a crashed AgentOS keeps
    a live WhatsApp session nobody is reading.
  - stdio backpressure is the OS's problem rather than ours.

WHAT THE CREDENTIALS ARE
========================
`auth/` is a complete WhatsApp session — equivalent to the phone for sending and
reading. It is written 0700 and never leaves the machine, `state()` never returns
it, and `logout()` deletes it rather than merely disconnecting, because a
"disconnected" device whose keys are still on disk is still a linked device.

THE STATE MACHINE
=================
    off ──start()──▶ starting ──▶ qr ──(scanned)──▶ ready
                        │           │                 │
                        └──error◀───┴──(timeout)──────┘
                                        logout() ──▶ off (auth deleted)

`qr` is the only state with a deadline: the code rotates roughly every twenty
seconds and Baileys gives up after a few rounds. A card showing a stale QR is a
code that will not scan and says nothing about why, so every rotation is
broadcast and the panel redraws.

Three faces (per CLAUDE.md):
  GUI  Settings → Channels → WhatsApp, when mode is `link`: the QR, or who it is
       linked as.
  TUI  `bento channels whatsapp --link` prints the QR as text in the terminal —
       the one place a QR genuinely has to be ASCII, since a headless Pi over SSH
       is exactly where you cannot open a settings page.
  SUI  identical to GUI.
"""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import time
from pathlib import Path

from . import config as cfgmod

#: Where the bridge and its credentials live. Under AGENTOS_HOME so a factory
#: reset takes the WhatsApp session with it — leaving a linked device behind
#: after "wipe everything" would be the worst possible interpretation of it.
def home() -> Path:
    return cfgmod.AGENTOS_HOME / "whatsapp-bridge"


def auth_dir() -> Path:
    return home() / "auth"


def script_path() -> Path:
    return home() / "bridge.mjs"


#: How long a fresh QR is worth showing before the bridge gives up on the round.
QR_TTL = 60
#: Restart backoff after an unexpected close, in seconds. A logout is NOT retried.
BACKOFF = (2, 5, 15, 30, 60)

BRIDGE_PKGS = ["@whiskeysockets/baileys@6", "qrcode@1"]

# ---------------------------------------------------------------------------
# The Node side
# ---------------------------------------------------------------------------
#
# Deliberately tiny, and written from here rather than shipped as a file: it has
# to be regenerated when this module changes, and a stale copy on an upgraded
# machine is exactly the class of bug `session.config_is_stale()` exists for.
# `install()` always rewrites it.

BRIDGE_JS = r"""// Generated by agentos/whatsapp_link.py — do not edit; reinstall to regenerate.
// Speaks newline-delimited JSON on stdout, reads commands on stdin.
import { makeWASocket, useMultiFileAuthState, DisconnectReason } from '@whiskeysockets/baileys'
import QR from 'qrcode'

const AUTH = process.argv[2]
const out = o => process.stdout.write(JSON.stringify(o) + '\n')

let sock = null

async function start () {
  const { state, saveCreds } = await useMultiFileAuthState(AUTH)
  sock = makeWASocket({ auth: state, printQRInTerminal: false, syncFullHistory: false })
  sock.ev.on('creds.update', saveCreds)

  sock.ev.on('connection.update', async u => {
    if (u.qr) {
      // Both shapes at once: an SVG for the desktop and the raw payload so a
      // terminal can draw the same code as ASCII. Rendering it twice in two
      // places is how the two surfaces end up showing different codes.
      progressed = true
      const svg = await QR.toString(u.qr, { type: 'svg', margin: 1, width: 260 })
      out({ t: 'qr', svg, payload: u.qr })
    }
    if (u.connection === 'open') {
      progressed = true
      out({ t: 'ready', me: (sock.user && sock.user.id) || '' })
    }
    if (u.connection === 'close') {
      progressed = true
      const code = (u.lastDisconnect && u.lastDisconnect.error
                    && u.lastDisconnect.error.output
                    && u.lastDisconnect.error.output.statusCode) || 0
      // loggedOut means the phone revoked this device: the credentials on disk
      // are now worthless and reconnecting with them loops forever.
      out({ t: 'closed', code, logged_out: code === DisconnectReason.loggedOut })
      process.exit(code === DisconnectReason.loggedOut ? 2 : 1)
    }
  })

  sock.ev.on('messages.upsert', ev => {
    if (ev.type !== 'notify') return
    for (const m of ev.messages || []) {
      if (!m.message || m.key.fromMe) continue
      const jid = m.key.remoteJid || ''
      if (jid.endsWith('@g.us')) continue          // groups are not paired chats
      const text = m.message.conversation
        || (m.message.extendedTextMessage && m.message.extendedTextMessage.text)
        || ''
      out({ t: 'message', id: m.key.id || '', from: jid.split('@')[0],
            name: m.pushName || '', text,
            kind: text ? 'text' : Object.keys(m.message)[0] || 'unknown' })
    }
  })
}

// If nothing has happened by now, nothing is going to: no QR, no connection, no
// error. Found by running it on a machine whose egress to web.whatsapp.com was
// blocked — the process sat silent and then exited 0, which the card read as
// "off" rather than "this machine cannot reach WhatsApp".
const CONNECT_DEADLINE = 25000
let progressed = false
setTimeout(() => {
  if (progressed) return
  out({ t: 'error', fatal: true,
        error: 'could not reach WhatsApp in 25s — check this machine\'s internet '
             + 'access (a proxy or firewall that blocks web.whatsapp.com will do this)' })
  process.exit(1)
}, CONNECT_DEADLINE)

let buf = ''
process.stdin.on('data', async d => {
  buf += d
  let i
  while ((i = buf.indexOf('\n')) >= 0) {
    const line = buf.slice(0, i); buf = buf.slice(i + 1)
    if (!line.trim()) continue
    let c; try { c = JSON.parse(line) } catch (e) { continue }
    try {
      if (c.t === 'send' && sock) {
        await sock.sendMessage(c.to + '@s.whatsapp.net', { text: c.text })
        out({ t: 'sent', ref: c.ref || '' })
      } else if (c.t === 'logout') {
        if (sock) await sock.logout().catch(() => {})
        out({ t: 'closed', code: 401, logged_out: true }); process.exit(2)
      }
    } catch (e) { out({ t: 'error', ref: c.ref || '', error: String(e && e.message || e) }) }
  }
})

start().catch(e => { out({ t: 'error', error: String(e && e.message || e) }); process.exit(1) })
"""


# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------

def node_path() -> str:
    return shutil.which("node") or ""


def installed() -> bool:
    """Is the bridge ready to run? The probe is the modules being there, never a
    remembered flag — an `npm install` that half-finished must read as missing."""
    return bool(node_path()) and (home() / "node_modules" / "@whiskeysockets" / "baileys").is_dir()


def why_not() -> str:
    """The sentence the consent card shows when it cannot be installed."""
    if not node_path():
        return ("Node.js is not on this machine. The WhatsApp Web bridge is a small "
                "Node program (Baileys, MIT) — install Node 18 or newer and this "
                "becomes available.")
    if not installed():
        return "The bridge has not been downloaded yet."
    return ""


async def install() -> dict:
    """Fetch the bridge into AGENTOS_HOME. Called only after the consent card.

    No sudo, no system packages: everything lands under the user's own AgentOS
    home, so this never needs the privilege ladder in components.py and never
    changes anything outside it.
    """
    node = node_path()
    if not node:
        return {"ok": False, "message": why_not()}
    npm = shutil.which("npm")
    if not npm:
        return {"ok": False, "message": "npm is not on this machine — it ships with Node.js."}
    d = home()
    d.mkdir(parents=True, exist_ok=True)
    (d / "package.json").write_text(json.dumps({"name": "agentos-whatsapp-bridge",
                                                "private": True, "type": "module"}, indent=1))
    proc = await asyncio.create_subprocess_exec(
        npm, "install", "--no-audit", "--no-fund", "--loglevel=error", *BRIDGE_PKGS,
        cwd=str(d), stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT)
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=900)
    except asyncio.TimeoutError:
        proc.kill()
        return {"ok": False, "message": "the download timed out after 15 minutes"}
    if proc.returncode != 0 or not installed():
        return {"ok": False, "message": (out or b"").decode()[-400:] or "npm install failed"}
    # Always rewritten, never merely created: an upgraded AgentOS whose bridge
    # script is from the previous version is the stale-generated-file bug again.
    script_path().write_text(BRIDGE_JS)
    return {"ok": True, "message": "WhatsApp Web bridge installed."}


# ---------------------------------------------------------------------------
# The running bridge
# ---------------------------------------------------------------------------

class LinkBridge:
    """Owns the Node child process and the link state machine.

    One instance for the whole server, created at startup but NOT started: a
    machine that has never asked for WhatsApp must not have a WhatsApp process.
    """

    def __init__(self, cfg: dict, store, broadcast, on_message=None):
        self.cfg = cfg
        self.store = store
        self.broadcast = broadcast
        self.on_message = on_message      # async (wa_id, name, text, kind, msg_id)
        self.state = "off"                # off | starting | qr | ready | error
        self.error = ""
        self.me = ""
        self.qr_svg = ""
        self.qr_payload = ""
        self.qr_at = 0.0
        self._proc: asyncio.subprocess.Process | None = None
        self._task: asyncio.Task | None = None
        self._stop = False
        self._tries = 0
        self._acks: dict[str, asyncio.Future] = {}
        self._seq = 0

    # -- state ---------------------------------------------------------------

    def status(self) -> dict:
        """What the card draws. Never includes credentials, and never the raw QR
        payload once it has aged out — a stale code that still renders is worse
        than an empty box, because it fails silently in the user's hand."""
        fresh = self.state == "qr" and (time.time() - self.qr_at) < QR_TTL
        return {"installed": installed(), "why": why_not(), "state": self.state,
                "error": self.error, "me": self.me,
                "qr_svg": self.qr_svg if fresh else "",
                "qr_payload": self.qr_payload if fresh else "",
                "linked": self.state == "ready"}

    def linked(self) -> bool:
        return self.state == "ready"

    # -- lifecycle -----------------------------------------------------------

    async def start(self) -> dict:
        if not installed():
            return {"ok": False, "error": why_not()}
        if self._task and not self._task.done():
            return {"ok": True, "already": True}
        self._stop = False
        self._tries = 0
        self.error = ""
        self.state = "starting"
        self._task = asyncio.create_task(self._supervise())
        return {"ok": True}

    async def stop(self):
        """Stop the process, keep the credentials. Used on shutdown — this is a
        pause, not an unlink, so the next start goes straight back to `ready`."""
        self._stop = True
        if self._proc and self._proc.returncode is None:
            self._proc.terminate()
            try:
                await asyncio.wait_for(self._proc.wait(), 5)
            except asyncio.TimeoutError:
                self._proc.kill()
        if self._task:
            self._task.cancel()
        self.state = "off"

    async def logout(self) -> dict:
        """Unlink, and DELETE the credentials.

        Disconnecting alone would leave a full WhatsApp session on disk that the
        phone still lists as a linked device — "unlinked" has to mean the keys are
        gone, or the word is a lie.
        """
        if self._proc and self._proc.returncode is None:
            await self._cmd({"t": "logout"})
            try:
                await asyncio.wait_for(self._proc.wait(), 8)
            except asyncio.TimeoutError:
                pass
        await self.stop()
        shutil.rmtree(auth_dir(), ignore_errors=True)
        self.me = ""
        self.qr_svg = self.qr_payload = ""
        self.state = "off"
        try:
            self.store.log("whatsapp", "link: unlinked and forgot the credentials")
        except Exception:
            pass
        await self._announce()
        return {"ok": True}

    async def _supervise(self):
        """Run the child, and bring it back when it dies unexpectedly.

        A logout is NOT retried: the credentials are void, so reconnecting with
        them is an infinite loop that looks to the user like "it keeps failing"
        rather than "you need to scan again".
        """
        while not self._stop:
            code = await self._run_once()
            if self._stop or code == 2:          # 2 == logged out, needs a new scan
                break
            self._tries = min(self._tries + 1, len(BACKOFF) - 1)
            wait = BACKOFF[self._tries]
            self.state = "error"
            self.error = self.error or f"the bridge stopped; retrying in {wait}s"
            await self._announce()
            try:
                await asyncio.sleep(wait)
            except asyncio.CancelledError:
                break
        if not self._stop and self.state != "ready":
            self.state = "off" if self.state == "off" else self.state
            await self._announce()

    async def _run_once(self) -> int:
        d = home()
        auth_dir().mkdir(parents=True, exist_ok=True)
        os.chmod(auth_dir(), 0o700)              # a full WhatsApp session
        try:
            self._proc = await asyncio.create_subprocess_exec(
                node_path(), str(script_path()), str(auth_dir()), cwd=str(d),
                stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE)
        except Exception as e:
            self.state, self.error = "error", str(e)[:200]
            await self._announce()
            return 1
        assert self._proc.stdout is not None
        try:
            async for raw in self._proc.stdout:
                line = raw.decode(errors="replace").strip()
                if not line:
                    continue
                try:
                    ev = json.loads(line)
                except Exception:
                    continue
                await self._event(ev)
        except asyncio.CancelledError:
            raise
        except Exception as e:
            self.error = str(e)[:200]
        rc = await self._proc.wait()
        if rc == 0 and self.state == "starting":
            # Exited cleanly having said nothing at all. That is not success — it
            # is the bridge failing to reach WhatsApp, and reporting it as "off"
            # is the silent-failure mode this whole module is written against.
            self.error = ("the bridge started and then stopped without reaching "
                          "WhatsApp — check this machine's internet access")
            rc = 1
        if rc not in (0, 2) and not self.error:
            err = b""
            if self._proc.stderr is not None:
                err = await self._proc.stderr.read()
            self.error = (err.decode(errors="replace").strip()[-200:]
                          or f"the bridge exited with {rc}")
        return rc

    async def _event(self, ev: dict):
        t = ev.get("t")
        if t == "qr":
            self.state = "qr"
            self.qr_svg = ev.get("svg") or ""
            self.qr_payload = ev.get("payload") or ""
            self.qr_at = time.time()
            self._tries = 0
            await self._announce()
        elif t == "ready":
            self.state = "ready"
            self.me = ev.get("me") or ""
            self.qr_svg = self.qr_payload = ""
            self.error = ""
            self._tries = 0
            try:
                self.store.log("whatsapp", f"link: connected as {self.me.split(':')[0]}")
            except Exception:
                pass
            await self._announce()
        elif t == "closed":
            if ev.get("logged_out"):
                # The phone revoked us. Say so and clear the keys, rather than
                # retrying forever against credentials that cannot work.
                shutil.rmtree(auth_dir(), ignore_errors=True)
                self.state, self.me = "off", ""
                self.error = "the phone unlinked this device — scan again to reconnect"
            else:
                self.state = "error"
            await self._announce()
        elif t == "error":
            fut = self._acks.pop(ev.get("ref") or "", None)
            if fut and not fut.done():
                fut.set_result(ev.get("error") or "send failed")
            else:
                self.error = ev.get("error") or ""
                if ev.get("fatal"):
                    self.state = "error"
                    await self._announce()
        elif t == "sent":
            fut = self._acks.pop(ev.get("ref") or "", None)
            if fut and not fut.done():
                fut.set_result("")
        elif t == "message" and self.on_message:
            await self.on_message(ev.get("from") or "", ev.get("name") or "",
                                  ev.get("text") or "", ev.get("kind") or "text",
                                  ev.get("id") or "")

    async def _announce(self):
        try:
            await self.broadcast({"type": "whatsapp_link", "state": self.state})
        except Exception:
            pass

    # -- outbound ------------------------------------------------------------

    async def _cmd(self, obj: dict):
        if not self._proc or self._proc.stdin is None or self._proc.returncode is not None:
            return
        self._proc.stdin.write((json.dumps(obj) + "\n").encode())
        await self._proc.stdin.drain()

    async def send(self, wa_id: str, text: str, timeout: float = 30) -> str:
        """'' on success, or a sentence. Waits for the bridge's ack rather than
        assuming: a write to a pipe succeeds long before WhatsApp accepts it, and
        "sent" that only means "handed to a subprocess" is the kind of success
        report that makes a delivery bug impossible to find."""
        if self.state != "ready":
            return ("WhatsApp is not linked — scan the QR in Settings → Channels → "
                    "WhatsApp")
        self._seq += 1
        ref = str(self._seq)
        fut: asyncio.Future = asyncio.get_event_loop().create_future()
        self._acks[ref] = fut
        await self._cmd({"t": "send", "to": wa_id, "text": text, "ref": ref})
        try:
            return await asyncio.wait_for(fut, timeout)
        except asyncio.TimeoutError:
            self._acks.pop(ref, None)
            return "the bridge did not confirm the message within 30s"


# ---------------------------------------------------------------------------
# The terminal face
# ---------------------------------------------------------------------------

def qr_ascii(payload: str) -> str:
    """The QR as text, for `bento channels whatsapp --link` over SSH.

    Rendered from the same payload the desktop draws as SVG, so the two surfaces
    can never show different codes. Returns '' when there is nothing to draw —
    the caller says why rather than printing an empty box.
    """
    if not payload:
        return ""
    try:
        import qrcode                      # optional; only the TUI path needs it
    except Exception:
        return ""
    q = qrcode.QRCode(border=1)
    q.add_data(payload)
    q.make(fit=True)
    m = q.get_matrix()
    # Two rows per line with half-blocks: a QR drawn one row per line is twice as
    # tall as it is wide in a terminal and will not scan.
    rows = []
    for y in range(0, len(m), 2):
        top, bot = m[y], m[y + 1] if y + 1 < len(m) else [False] * len(m[y])
        rows.append("".join("█" if t and b else "▀" if t else "▄" if b else " "
                            for t, b in zip(top, bot)))
    return "\n".join(rows)
